[versions]
agp = "8.2.2"
kotlin = "1.9.22"
appcompat = "1.6.1"
leanback = "1.0.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
