// <auto-generated />
using System;
using AcademiaFight.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcademiaFight.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630022218_AddFirebaseUid")]
    partial class AddFirebaseUid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Academia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("NoticiasAtivas")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PlanoExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanoTipo")
                        .HasColumnType("integer");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subdominio");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("TemplateContrato")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("academias", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.AtestadoMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<bool>("AlertaVencimentoEnviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alerta_vencimento_enviado");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<bool>("AnexadoPorAcademia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("anexado_por_academia");

                    b.Property<Guid?>("AnexadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("anexado_por_id");

                    b.Property<string>("ArquivoBase64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arquivo_base64");

                    b.Property<string>("ArquivoMimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("arquivo_mime_type");

                    b.Property<string>("ArquivoNome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("arquivo_nome");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_validade");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId", "Status");

                    b.HasIndex("AlunoId", "DataValidade");

                    b.ToTable("atestados_medicos", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Conquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<string>("IconeUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icone_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("PontosXpBonus")
                        .HasColumnType("integer")
                        .HasColumnName("pontos_xp_bonus");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("conquistas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Registrou sua primeira presença na academia.",
                            IconeUrl = "star",
                            Nome = "Primeiro Treino",
                            PontosXpBonus = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Treinou 5 vezes em 7 dias corridos.",
                            IconeUrl = "fire",
                            Nome = "Semana Perfeita",
                            PontosXpBonus = 25,
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "100% de frequencia em um mes.",
                            IconeUrl = "trophy",
                            Nome = "Mes Invicto",
                            PontosXpBonus = 50,
                            Tipo = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Conquistou sua primeira faixa.",
                            IconeUrl = "medal",
                            Nome = "Graduado",
                            PontosXpBonus = 100,
                            Tipo = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "10 presencas consecutivas sem faltar.",
                            IconeUrl = "bolt",
                            Nome = "Sequencia de 10",
                            PontosXpBonus = 30,
                            Tipo = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "50 presencas totais registradas.",
                            IconeUrl = "muscle",
                            Nome = "Veterano",
                            PontosXpBonus = 80,
                            Tipo = 6
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "100 presencas totais - voce e uma lenda desta academia!",
                            IconeUrl = "crown",
                            Nome = "Lenda",
                            PontosXpBonus = 150,
                            Tipo = 7
                        });
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.ConquistaAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ConquistaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conquista_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DesbloqueadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desbloqueada_em");

                    b.Property<bool>("VistaPeloAluno")
                        .HasColumnType("boolean")
                        .HasColumnName("vista_pelo_aluno");

                    b.HasKey("Id");

                    b.HasIndex("ConquistaId");

                    b.HasIndex("AlunoId", "ConquistaId")
                        .IsUnique();

                    b.ToTable("conquistas_aluno", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConteudoHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAssinatura")
                        .HasColumnType("text");

                    b.Property<Guid?>("MatriculaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModalidadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModeloContratoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeAssinou")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TokenPublico")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("MatriculaId");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("ModeloContratoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Faixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cor");

                    b.Property<string>("CorBarra")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#000000")
                        .HasColumnName("cor_barra");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("MaxGraus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("max_graus");

                    b.Property<Guid>("ModalidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("modalidade_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("RequisitosMesesMinimos")
                        .HasColumnType("integer")
                        .HasColumnName("requisitos_meses_minimos");

                    b.Property<int>("RequisitosPresencasMinimas")
                        .HasColumnType("integer")
                        .HasColumnName("requisitos_presencas_minimas");

                    b.Property<bool>("TemGraus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tem_graus");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("ModalidadeId", "Ordem");

                    b.ToTable("faixas", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_admissao");

                    b.Property<string>("Permissoes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissoes");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Graduacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovado");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CertificadoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("certificado_url");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataExame")
                        .HasColumnType("date")
                        .HasColumnName("data_exame");

                    b.Property<Guid>("FaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("faixa_id");

                    b.Property<int>("Grau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("grau");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professor_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("FaixaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("AlunoId", "FaixaId");

                    b.ToTable("graduacoes", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.GrupoFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.ToTable("GruposFamiliares");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Sala")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sala");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid")
                        .HasColumnName("turma_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.LancamentoPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.Property<Guid>("RankingCustomId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranking_custom_id");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("AcademiaId", "AlunoId");

                    b.HasIndex("RankingCustomId", "AlunoId");

                    b.ToTable("lancamentos_ponto", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid")
                        .HasColumnName("turma_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("AlunoId", "TurmaId", "Ativo");

                    b.ToTable("matriculas", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Modalidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("SistemaFaixasJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("sistema_faixas_json");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.ToTable("modalidades", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.ModeloContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConteudoHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.ToTable("ModelosContrato");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Noticia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Conteudo")
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("ImagemBase64")
                        .HasColumnType("TEXT")
                        .HasColumnName("imagem_base64");

                    b.Property<bool>("Publicada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("publicada");

                    b.Property<DateTime?>("PublicadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_em");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resumo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("AcademiaId", "PublicadaEm");

                    b.ToTable("noticias", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChaveDedup")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("AlunoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.ParQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataPreenchimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_preenchimento");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<bool>("R1")
                        .HasColumnType("boolean")
                        .HasColumnName("r1");

                    b.Property<bool>("R10")
                        .HasColumnType("boolean")
                        .HasColumnName("r10");

                    b.Property<bool>("R2")
                        .HasColumnType("boolean")
                        .HasColumnName("r2");

                    b.Property<bool>("R3")
                        .HasColumnType("boolean")
                        .HasColumnName("r3");

                    b.Property<bool>("R4")
                        .HasColumnType("boolean")
                        .HasColumnName("r4");

                    b.Property<bool>("R5")
                        .HasColumnType("boolean")
                        .HasColumnName("r5");

                    b.Property<bool>("R6")
                        .HasColumnType("boolean")
                        .HasColumnName("r6");

                    b.Property<bool>("R7")
                        .HasColumnType("boolean")
                        .HasColumnName("r7");

                    b.Property<bool>("R8")
                        .HasColumnType("boolean")
                        .HasColumnName("r8");

                    b.Property<bool>("R9")
                        .HasColumnType("boolean")
                        .HasColumnName("r9");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AcademiaId", "AlunoId")
                        .IsUnique();

                    b.ToTable("par_qs", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxaMatricula")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorMensal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.PontoRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId", "AlunoId");

                    b.HasIndex("AlunoId", "Data");

                    b.ToTable("pontos_ranking", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Presenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<bool>("Confirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("confirmado");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<TimeOnly>("HoraCheckin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_checkin");

                    b.Property<Guid>("HorarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("horario_id");

                    b.Property<int>("MetodoCheckin")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_checkin");

                    b.Property<string>("ObservacoesProfessor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes_professor");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("AlunoId", "HorarioId", "Data")
                        .IsUnique();

                    b.ToTable("presencas", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.RankingCustom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IncluirPontosManuais")
                        .HasColumnType("boolean")
                        .HasColumnName("incluir_pontos_manuais");

                    b.Property<bool>("IncluirPresencas")
                        .HasColumnType("boolean")
                        .HasColumnName("incluir_presencas");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("PesoManuais")
                        .HasColumnType("integer")
                        .HasColumnName("peso_manuais");

                    b.Property<int>("PesoPresencas")
                        .HasColumnType("integer")
                        .HasColumnName("peso_presencas");

                    b.Property<bool>("VisivelParaAluno")
                        .HasColumnType("boolean")
                        .HasColumnName("visivel_para_aluno");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId", "Ativo");

                    b.ToTable("rankings_custom", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_maxima");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("ModalidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("modalidade_id");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professor_id");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("academia_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CatracaDeviceUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasColumnType("text");

                    b.Property<string>("ContatoEmergenciaTelefone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text");

                    b.Property<string>("FotoBase64")
                        .HasColumnType("text");

                    b.Property<Guid?>("GrupoFamiliarId")
                        .HasColumnType("uuid");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NivelAtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<Guid?>("PlanoId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reset_password_token");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_password_token_expiry");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TipoPlano")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.Property<int>("XpMensal")
                        .HasColumnType("integer");

                    b.Property<int>("XpTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademiaId");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("PlanoId");

                    b.HasIndex("Email", "AcademiaId")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.AtestadoMedico", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.ConquistaAluno", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Conquista", "Conquista")
                        .WithMany()
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Conquista");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Matricula", "Matricula")
                        .WithMany()
                        .HasForeignKey("MatriculaId");

                    b.HasOne("AcademiaFight.Domain.Entities.Modalidade", "Modalidade")
                        .WithMany()
                        .HasForeignKey("ModalidadeId");

                    b.HasOne("AcademiaFight.Domain.Entities.ModeloContrato", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloContratoId");

                    b.Navigation("Academia");

                    b.Navigation("Aluno");

                    b.Navigation("Matricula");

                    b.Navigation("Modalidade");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Faixa", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Modalidade", "Modalidade")
                        .WithMany("Faixas")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany("Funcionarios")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Graduacao", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Faixa", "Faixa")
                        .WithMany("Graduacoes")
                        .HasForeignKey("FaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Aluno");

                    b.Navigation("Faixa");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.GrupoFamiliar", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Horario", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Turma", "Turma")
                        .WithMany("Horarios")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.LancamentoPonto", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.RankingCustom", "RankingCustom")
                        .WithMany("Lancamentos")
                        .HasForeignKey("RankingCustomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("RankingCustom");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Modalidade", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany("Modalidades")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.ModeloContrato", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Noticia", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Academia");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.ParQ", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Plano", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.PontoRanking", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Presenca", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Horario", "Horario")
                        .WithMany("Presencas")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Aluno");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.RankingCustom", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany()
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Turma", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany("Turmas")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Modalidade", "Modalidade")
                        .WithMany("Turmas")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.Usuario", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academia");

                    b.Navigation("Modalidade");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AcademiaFight.Domain.Entities.Academia", "Academia")
                        .WithMany("Usuarios")
                        .HasForeignKey("AcademiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaFight.Domain.Entities.GrupoFamiliar", "GrupoFamiliar")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoFamiliarId");

                    b.HasOne("AcademiaFight.Domain.Entities.Plano", "Plano")
                        .WithMany("Alunos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Academia");

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Academia", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Modalidades");

                    b.Navigation("Turmas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Faixa", b =>
                {
                    b.Navigation("Graduacoes");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.GrupoFamiliar", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Horario", b =>
                {
                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Modalidade", b =>
                {
                    b.Navigation("Faixas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Plano", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.RankingCustom", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("AcademiaFight.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
