// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9NvRXPIH1yUJQEtsEKFRiV36OgH9KMw',
    appId: '1:376094928692:web:cb7c3e290e7ea2db3e3f61',
    messagingSenderId: '376094928692',
    projectId: 'sensei-manager-d64c0',
    authDomain: 'sensei-manager-d64c0.firebaseapp.com',
    storageBucket: 'sensei-manager-d64c0.firebasestorage.app',
    measurementId: 'G-KK2SEEV0Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9bd3DffzqOqYxiR0SHS29--YD9T_KGT8',
    appId: '1:376094928692:android:419bcc0bee9afa463e3f61',
    messagingSenderId: '376094928692',
    projectId: 'sensei-manager-d64c0',
    storageBucket: 'sensei-manager-d64c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1qg976R4zpsA0Evnhlxu3gt8pSPrD2o',
    appId: '1:376094928692:ios:ac7a3728d7ca031c3e3f61',
    messagingSenderId: '376094928692',
    projectId: 'sensei-manager-d64c0',
    storageBucket: 'sensei-manager-d64c0.firebasestorage.app',
    iosBundleId: 'br.com.hg2tecnologia.senseimanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1qg976R4zpsA0Evnhlxu3gt8pSPrD2o',
    appId: '1:376094928692:ios:000aa4b1b13558923e3f61',
    messagingSenderId: '376094928692',
    projectId: 'sensei-manager-d64c0',
    storageBucket: 'sensei-manager-d64c0.firebasestorage.app',
    iosBundleId: 'com.tatame.tatame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD9NvRXPIH1yUJQEtsEKFRiV36OgH9KMw',
    appId: '1:376094928692:web:caacc4767ccb0f173e3f61',
    messagingSenderId: '376094928692',
    projectId: 'sensei-manager-d64c0',
    authDomain: 'sensei-manager-d64c0.firebaseapp.com',
    storageBucket: 'sensei-manager-d64c0.firebasestorage.app',
    measurementId: 'G-PW2CTRBV7X',
  );
}
